In [49]:
import pandas as pd

In [58]:
dados = pd.read_csv('datasets/fifa19-utf8.csv')

# dados_xlsx = pd.read_excel('datasets/fifa19-utf8.xlsx')

# dados_txt = pd.read_csv('datasets/fifa19-utf8.txt', sep='\t')

# dados_html = pd.read_html("https://en.wikipedia.org/wiki/List_of_presidents_of_the_United_States", storage_options=
                        #   {"User-Agent": "Mozilla/5.0"})

# dados.head(8) # primeiros
# dados.tail()  # últimos
# dados.columns # colunas
# dados.index  # index final e inicial
# dados['Name'] # 5 primeiros nomes e 5 últimos
# dados[['Name', 'Nationality', 'Wage']]

In [8]:
# dados.iloc[1] # localiza a linha 1 do dataframe
# dados.iloc[0:4] # localiza a linha 0 a 4 do dataframe
dados.iloc[3,2]  # localiza a linha 3 e coluna 2 do dataframe

'De Gea'

In [18]:
# dados.loc[dados['Nationality'] == 'Brazil'] # localiza todos os jogadores brasileiros
# dados.loc[dados['Age'] == 41] # localiza todos os jogadores com 41 anos

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
1120,1120,156092,J. Villar,41.0,https://cdn.sofifa.org/players/4/19/156092.png,Paraguay,https://cdn.sofifa.org/flags/58.png,77.0,77,NaN,...,55.0,13.0,13.0,14.0,75.0,75.0,74.0,78.0,77.0,NaN
4228,4228,3665,B. Nivet,41.0,https://cdn.sofifa.org/players/4/19/3665.png,France,https://cdn.sofifa.org/flags/18.png,71.0,71,ESTAC Troyes,...,82.0,58.0,56.0,43.0,11.0,7.0,8.0,14.0,7.0,NaN
7225,7225,142998,C. Muñoz,41.0,https://cdn.sofifa.org/players/4/19/142998.png,Argentina,https://cdn.sofifa.org/flags/52.png,68.0,68,CD Universidad de Concepción,...,62.0,18.0,14.0,19.0,67.0,65.0,68.0,71.0,68.0,€84K
12192,12192,208927,H. Sulaimani,41.0,https://cdn.sofifa.org/players/4/19/208927.png,Saudi Arabia,https://cdn.sofifa.org/flags/183.png,63.0,63,Ohod Club,...,67.0,62.0,66.0,63.0,15.0,8.0,15.0,14.0,13.0,NaN
15426,15426,18745,M. Tyler,41.0,https://cdn.sofifa.org/players/4/19/18745.png,England,https://cdn.sofifa.org/flags/14.png,59.0,59,Peterborough United,...,57.0,24.0,16.0,17.0,61.0,54.0,54.0,63.0,55.0,€18K

In [34]:
# dados.sort_values('Name') # ordena os nomes em ordem alfabética
# dados.sort_values('Age') # ordena os jogadores em ordem crescente de idade
# dados.sort_values('Age', ascending=False) # ordena os jogadores em ordem decrescente de idade
# dados.sort_values(['Name', 'Age'], ascending=False) # ordena os jogadores em ordem decrescente de idade e em ordem alfabética de nome
dados.sort_values('Weight', ascending=False)[['Name', 'Weight']].head(1) # Localiza o jogador mais pesado do FIFA 19

              Name  Weight
9501  A. Akinfenwa  243lbs

In [63]:
dados = pd.read_csv('datasets/fifa19-utf8.csv')

# Cria a nova coluna antes de eliminar as outras
dados['Total'] = dados['Acceleration'] + dados['Agility'] + dados['Reactions']

# Mantém apenas as colunas que queremos visualizar
dados = dados[['Name', 'Total']]

# Ordena do maior para o menor e pega os 10 primeiros
dados = dados.sort_values('Total', ascending=False).head(10)

dados

                 Name  Total
2           Neymar Jr  284.0
5           E. Hazard  279.0
0            L. Messi  277.0
26           M. Salah  276.0
25          K. Mbappé  275.0
50         D. Mertens  275.0
60        R. Sterling  275.0
65      Douglas Costa  274.0
1   Cristiano Ronaldo  272.0
58            S. Mané  272.0